// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uswzqnvntracnrzkodyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzd3pxbnZudHJhY25yemtvZHlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMjA4ODYsImV4cCI6MjA2NjU5Njg4Nn0.cnNG-mvI7phP896eDVvP69z6LJcLeEkKsW0iBkIZ9P4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);